name: epicur_ia_asistente_culinario_inteligente
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  flutter_dotenv: ^6.0.1
  image_picker: ^1.2.1
  supabase_flutter: ^2.5.0
  crypto: ^3.0.7
  google_sign_in: ^7.2.0
  flutter_tts: ^4.2.5
  speech_to_text: ^7.4.0
  permission_handler: ^12.0.1
  audioplayers: ^6.7.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_icon.png
    - .env